In [74]:
# Matrix class

import numpy as np
from ypstruct import struct

class Matrix:
    """
    MATRIX: A matrix class:
    
       A = Matrix(2,5)
       B = Matrix(2,5)
       C = A+B or 
       D = A or (B and C)
       D = C+2.45 - A*5.2
       a12 = A[1,2]
       A12 = A[i1,i2]          # get submatrix
       A.set([i1,i2],A12)      # set submatrix
       A12 = A[(1,3),(3,6)]
       AT = A.T
       a = A()                 
       A = a[]                 # reshape to original matrix
       C = A*B                 # element wise multiplication
       b = A@x                 # oprdinary matrix multiplication
       
    Supporting Functions:

       isa    check if object is of given type
       rand   create random matrix
       zeros  create matrix filled with zeros
       ones   create matrix filled with ones
       eye    create unity matrix
       
    See also: Matrix, rand, add, sub, mul, div, index
    """
    def __init__(self,m=None,n=None): return init(self,m,n)
    def __repr__(self): return repr(self)
    def __add__(self,other): return add(self,other)
    def __getitem__(self,i,j): return getitem(self,i,j)

#============================================================================
# a setting structure for the matrix module
#    --matrix__.rand           # random generator object
#    --matrix__.format         # print format
#============================================================================

__matrix__ = struct(rand=Rand(), format='short')

#============================================================================
# init Matrix        
#============================================================================

def init(o,m,n):
        m = 0 if m == None else m
        n = 0 if n == None else n
        o.M = np.zeros((m,n))

#============================================================================
# string representation of Matrix        
#============================================================================

def repr(o):
    m,n = o.M.shape
    length = 0
    for i in range(0,m):
        for j in range(0,n):
            s = "%g" % o.M[i,j]
            length = max(length,len(s))
    
    str = ""
    for i in range(0,m):
        s = ""
        for j in range(0,n):
            if length < 5:
                s = s + "%5g" % o.M[i,j]
            elif length < 8:
                s = s + "%9g" % o.M[i,j]
            else:
                s = s + "%12g" % o.M[i,j]
        s = s + "\n"
        str = str +s
    return str

#============================================================================
# add arg to Matrix        
#============================================================================

def add(o,other):
    m,n = size(o)
    result = Matrix(m,n)
    if isa(other,'int'):
        result.M = o.M + other
    else:
        result.M = o.M + other
    return result

#============================================================================
# function isa        
#============================================================================

def isa(arg,classname):
    """
    ISA  Return 1 (true) if A has the data type specified,
         otherwise 0 (false)

      ok = isa(123,'int')
      ok = isa(3.14159,'float')
      ok = isa("hello world",'str')
      ok = isa(Matrix(2,3),'Matrix')
    """
    return int(type(arg).__name__ == classname)

#============================================================================
# matrix sizes        
#============================================================================

def size(o):
    if isa(o,'ndarray'):
        m,n = o.shape
    elif isa(o,'Matrix'): 
        m,n = o.M.shape
    else:
        m = 1; n = 1
    return m,n

#============================================================================
# create a random matrix        
#============================================================================

class Rand:
    """
    RAND Pseudo random generator class

            rg = Random            # create random generator (seed = 0)
            rg = Random(seed)      # create random generator with given seed
            x = rg.rand()          # get random float 0.0 <= x <= 1.0
            n = rg.rand(nmax)      # get random integer 0 <= n < nmax
            M = rg.rand(m,n)       # get float random matrix in interval [0,1]
            M = rg.rand(m,n,nmax)  # get int random matrix with 0 <= M[i,j] < nmax
    """
    def __init__(self,seed=None):
        self.p = 1*2*3*5*7*11*13*17*19*23*29*31*37-1    # small prime
        self.P = 1*2*3*5*7*11*13*17*19*23*29*31*37*41+1 # large prime
        self.seed = 0 if seed == None else seed
        self.seed += (self.p+1)/2 
        
    def rand(self,m=None,n=None,nmax=None):
        if m == None:              # x = rg.rand()
            self.seed = ((self.seed+1) * self.P) % self.p
            return (self.seed / (self.p-1))
        elif n == None:            # x = rg.rand(nmax)
            self.seed = ((self.seed+1) * self.P) % self.p
            return self.seed % m
        elif nmax == None:         # x = rg.rand(m,n)
            o = Matrix(m,n)
            for i in range(0,m):
                for j in range(0,n):
                    o.M[i,j] = self.rand()
            return o
        else:
            o = Matrix(m,n)
            for i in range(0,m):
                for j in range(0,n):
                    o.M[i,j] = self.rand(nmax)
            return o
            
def rand(m=None,n=None,nmax=None):
    """
    RAND   Uniformly distributed random numbers. This function returns a
    random scalar drawn from the uniform distribution in the interval (0,1).

       X = rand
       X = rand(n)          # n x n matrix
       X = rand(m,n)
       X = rand(m,n,nmax)
       X = rand(size(A))
    """
    
    if m == None and n == None:
        return __matrix__.rand(1,1)
    elif n == None:
        if type(m) is tuple:
            m,n = m
            return __rand__.rand(m,m)
        else:
            return __rand__.rand(m,m)
    elif nmax == None:
        return __matrix__.rand(m,n)
    else:
        return __rand__.rand(m,n,nmax)


In [73]:
X=rand(1,20,7)
X


    5    2    2    6    5    4    5    6    2    4    1    1    6    1    4    1    3    4    1    2

In [72]:
A=Matrix(4,5)
A

    0    0    0    0    0
    0    0    0    0    0
    0    0    0    0    0
    0    0    0    0    0

In [43]:
A=A+2.178654388
A
A=A+1.12e37
A

    1.12e+37    1.12e+37    1.12e+37    1.12e+37    1.12e+37
    1.12e+37    1.12e+37    1.12e+37    1.12e+37    1.12e+37
    1.12e+37    1.12e+37    1.12e+37    1.12e+37    1.12e+37
    1.12e+37    1.12e+37    1.12e+37    1.12e+37    1.12e+37

In [16]:
type(A).__name__

'Matrix'

In [75]:
help(Matrix)

Help on class Matrix in module __main__:

class Matrix(builtins.object)
 |  Matrix(m=None, n=None)
 |  
 |  MATRIX: A matrix class:
 |  
 |     A = Matrix(2,5)
 |     B = Matrix(2,5)
 |     C = A+B or 
 |     D = A or (B and C)
 |     D = C+2.45 - A*5.2
 |     a12 = A[1,2]
 |     A12 = A[i1,i2]
 |     A12 = A[(1,3),(3,6)]
 |     AT = A.T
 |     a = A()                 
 |     A = a[]                 # reshape to original matrix
 |     C = A*B                 # element wise multiplication
 |     b = A@x                 # oprdinary matrix multiplication
 |     
 |  Supporting Functions:
 |  
 |     isa    check if object is of given type
 |     rand   create random matrix
 |     zeros  create matrix filled with zeros
 |     ones   create matrix filled with ones
 |     eye    create unity matrix
 |     
 |  See also: Matrix, rand, add, sub, mul, div, index
 |  
 |  Methods defined here:
 |  
 |  __add__(self, other)
 |  
 |  __getitem__(self, i, j)
 |  
 |  __init__(self, m=None, n=None)


In [105]:
from numpy import array,matrix,ndarray
a=array(1)
a+3



4

In [106]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)

"""
mat_slice = mat[:2,:2] # Simple indexing
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)
"""

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


'\nmat_slice = mat[:2,:2] # Simple indexing\nprint ("\nSliced matrix")\nprint(mat_slice)\nprint ("\nChange the sliced matrix")\nmat_slice[0,0] = 1000\nprint (mat_slice)\nprint("\nBut the original matrix? WHOA! It got changed too!")\nprint(mat)\n'

In [118]:
mat[0:1,:]

array([[11, 12, 13]])

In [114]:
a[:,2]

TypeError: list indices must be integers or slices, not tuple