In [3]:
# NumPy Slices

import numpy as np

mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [4]:
mat_slice = mat[:2,:2] # Simple indexing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [8]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
mat_slice


Change the sliced matrix


array([[1000,   12],
       [  21,   22]])

In [6]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)


But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [9]:
# Filter array by indices
mat

array([[1000,   12,   13],
       [  21,   22,   23],
       [  31,   32,   33]])

In [16]:
F = mat.flatten('F')
F

array([1000,   21,   31,   12,   22,   32,   13,   23,   33])

In [20]:
F[[2,3]]

array([31, 12])

In [30]:
g=np.array((0,1,2,3))
g

array([0, 1, 2, 3])

In [64]:
g=list((1,2,3,4))
g

[1, 2, 3, 4]

In [65]:
lst = [0,1,2,3]
print("lst:",lst)
print("type(lst):",type(lst).__name__)

lst: [0, 1, 2, 3]
type(lst): list


In [66]:
tup=(1,2,3)
print("tup:",tup)
print("type(tup):",type(tup).__name__)

tup: (1, 2, 3)
type(tup): tuple


In [85]:
a = np.array(lst)
print("a:",a)
g = np.array([i for i in range(0,4)])
print("g:",g)
x = np.arange(12)
print("x:",x)
print("type(x):",type(x).__name__)
X = x.reshape(3,4,order='F')
print("X:\n",X)
print("type(X):",type(X).__name__)


a: [0 1 2 3]
g: [0 1 2 3]
x: [ 0  1  2  3  4  5  6  7  8  9 10 11]
type(x): ndarray
X:
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
type(X): ndarray


In [86]:
x_slice = X[:2,:2] # Simple indexing
print ("\nSliced matrix")
print(x_slice)



Sliced matrix
[[0 3]
 [1 4]]


In [88]:
x_slice[1,1]=555
print("x_slice",x_slice)
print("X:\n",X)


x_slice [[  0   3]
 [  1 555]]
X:
 [[  0   3   6   9]
 [  1 555   7  10]
 [  2   5   8  11]]


In [92]:
g=slice(4,8)
x[g]

array([555,   5,   6,   7])

In [96]:
x[6]=66

In [97]:
x

array([  0,   1,  66,   3, 555,   5,  66,   7,   8,   9,  10,  11])

In [100]:
y=x[g]
y

array([555,   5,  66,   7])

In [101]:
x[6] = 77

In [103]:
print("x:",x)
print("y:",y)

x: [  0   1  66   3 555   5  77   7   8   9  10  11]
y: [555   5  77   7]
