In [1]:
#===============================================================================
# HTM package
#===============================================================================

from carabao.util import peek,poke,Random
from carabao.toy import Toy
from torch import zeros

#===============================================================================
# class: HTM layer
#===============================================================================

  # Layer(m,n,s,d)
  #   m: number of cells per minicolumn
  #   n: number of minicolumns
  #   s: number of synapses per distal segment
  #   d: number of distal segments

import torch

class Layer:
  from torch import zeros, rand
  def input(self,word,vocabulary):
    self.u = vocabulary[word]

  def __init__(self, m, n, s, d):
    self.m = m;  self.n = n;  self.s = s;  self.d = d;
    self.N = m*n;  self.M = s * d
    rand = Random(0)                    # create random generator @ seed = 0
    self.X = torch.zeros(m,n)
    self.Y = self.X
    self.u = None
    M0 = self.forbidden(self.s,self.d)
    P0 = torch.zeros(self.m,self.n)
    self.K = rand.cells(P0,M0,self.N)
    self.P = torch.rand(self.m,self.n,self.s,self.d)
    print("Layer ",self.m,"x",self.n,"cells @ ",self.s,"x",self.d,"synapses")

  def forbidden(self,m,n):              # setup forbidden matrix
    M = torch.zeros(m,n)
    for i in range(0,m):
      for j in range(0,n):
        M[i,j] = j*n + i
    return M

  def input(self,u):
      self.u = u;
      
  def print(self):
      print("u:\n",self.u)
      print("X:\n",self.X)
      print("Y:\n",self.Y)
      print("K:\n",self.K)
      print("K:\n",self.K)
     
      

In [2]:
toy = Toy()
V = toy.vocab()
print("V:\n",V)

u = V['Mary']
print("u:\n",u)
print("\n")

o = Layer(4,10,5,2)
o.input(u)
o.print()

V:
 {'Mary': [0, 0, 1, 0, 0, 1, 1, 1, 0, 0], 'John': [1, 0, 0, 1, 0, 1, 1, 0, 0, 0], 'likes': [0, 1, 0, 0, 0, 0, 0, 1, 1, 1], 'to': [0, 1, 0, 1, 1, 0, 0, 0, 0, 1]}
u:
 [0, 0, 1, 0, 0, 1, 1, 1, 0, 0]


Layer  4 x 10 cells @  5 x 2 synapses
u:
 [0, 0, 1, 0, 0, 1, 1, 1, 0, 0]
X:
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
Y:
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
K:
 tensor([[[[23,  6],
          [ 4, 30],
          [16, 37],
          [21, 38],
          [35, 20]],

         [[33, 10],
          [38, 31],
          [32,  2],
          [34,  6],
          [25, 19]],

         [[17,  5],
          [19, 25],
          [37,  0],
          [26, 24],
          [27, 11]],

      

In [3]:
o.X

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])