In [1]:
# test class Matrix and class Tensor

from numpy import array, zeros
from carabao.matrix import Matrix,Tensor, rand,eye,zeros,ones,size,min,max,magic


In [2]:
A=Matrix(2,3);A

[0 0 0; 0 0 0]

In [3]:
A+0.5

[0.5 0.5 0.5; 0.5 0.5 0.5]

In [4]:
Matrix()

[]

In [5]:
(A+0.5).T

[0.5 0.5; 0.5 0.5; 0.5 0.5]

In [6]:
Matrix(1,5).T+1

[1; 1; 1; 1; 1]

In [7]:
B=rand(3,4);B


[0.680268 0.0229485 0.144282 0.921875; 0.87457 0.284664 0.775658 0.0243347; 0.960743 0.931559 0.705115 0.79627]

In [8]:
max(B)

[0.960743 0.931559 0.775658 0.921875]

In [9]:
(9,6)==(9,7)

False

In [10]:
min(8,4)

4

In [11]:
max(8,4)

8

In [12]:
b=min(max(0.5,eye(3)));b
a=max(eye(3))

In [13]:
A=eye(3);A

[1 0 0; 0 1 0; 0 0 1]

In [14]:
A[1:2]

[0 1 0]

In [15]:
A==1

[1 0 0; 0 1 0; 0 0 1]

In [16]:
class Test:
    def __init__(self):
        self.K = magic(4)

    def __repr__(self):
        return self.K.__repr__()

    def __str__(self):
        return self.K.__str__()

    def __getitem__(self,idx):
        if isinstance(idx,int):
            print('integer:',idx)
        elif isinstance(idx,float):
            print('float:',idx)
        elif isinstance(idx,tuple):
            print('tuple:',idx)
            idx1,idx2 = idx
            if isinstance(idx1,slice):
                if isinstance(idx2,int):
                    idx2 = slice(idx2,idx2+1,None)
                print('slice1:',idx1,idx2)
                return self.K[idx1,idx2]
            elif isinstance(idx2,slice):
                if isinstance(idx1,int):
                    idx1 = slice(idx1,idx1+1,None)
                print('slice1:',idx1,idx2)
                return self.K[idx1,idx2]
        return idx

In [17]:
T=Test();T

[16 2 3 13; 5 11 10 8; 9 7 6 12; 4 14 15 1]

In [18]:
print('T:',T)
T[3,:]

T: [16 2 3 13; 5 11 10 8; 9 7 6 12; 4 14 15 1]
tuple: (3, slice(None, None, None))
slice1: slice(3, 4, None) slice(None, None, None)


[4 14 15 1]

In [28]:
A=magic(4);
K=Matrix([[1,2,5],[6,7,8]])
print('A:',A)
print('K:',K)
A.T[K]

A: [16 2 3 13; 5 11 10 8; 9 7 6 12; 4 14 15 1]
K: [1 2 5; 6 7 8]


[2 3 11; 10 8 9]