In [22]:
# class Matrix

from numpy import array, zeros

class Matrix:
    def __init__(self,m,n):
        self.shape = (m,n)
        self.data = zeros((m,n))

    def kappa(self,i,j=None):
        """
        self.kappa():  convert matrix indices to linear index or vice versa
        >>> Map().kappa(i:=1,j:=3)   # k = i+j*m
        13
        >>> Map().kappa(k:=13)       # i = k%m, j = k//m
        (1, 3)
        """

        m,n,d,s = self.shape
        if j is None:
            k = i
            return (k%m,k//m)
        else:
            return i + j*m


    def isa(self,obj,typ=None):
        if typ is None:
            print(type(obj),type(obj).__name__)
        return (type(obj).__name__ == typ)

    def __repr__(self,wide=False):   # string representation of list or matrix
        if isinstance(self.data,list):
            txt = "[";  M = array([self.data])
            #print("repr M:",M,type(M),M.shape)
        elif self.isa(self.data,'ndarray'):
            txt = "#[";  M = self.data
            if len(M.shape) == 1:
                txt = ":[";  M = self.data
                M = array([M])
        else:
            return self
    
        m,n = M.shape
        sepi = ''
        for i in range(0,m):
            txt += sepi;  sepi = '; ';  sepj = ''
            for j in range(0,n):
                if wide == False:
                    txt += sepj + "%g" % M[i,j]
                else:
                    s = "%4g" %M[i,j].item()
                    s = s if s[0:2] != '0.' else s[1:]
                    s = s if s[0:3] != '-0.' else '-'+s[2:]
                    txt += "%5s" % s
                sepj = ' '
        txt += ']'
        return txt


In [25]:
A=Matrix(0,0);A

#[]

In [57]:
import numpy as np

class Matrix(np.ndarray):
    """
    class Matrix: matrix wrapper for NumPy arrays
    >>> Matrix(0,0)
    []
    >>> Matrix(2,3)
    [[0 0 0][0 0 0]]
    >>> Matrix([1,2,3])
    [[1 2 3]]
    >>> Matrix([[1,2,3],[4,5,6]])
    [[1 2 3][4 5 6]]
    """
    def __new__(cls, arg1, arg2=1,data=None):
        if isinstance(arg1,np.ndarray):
            #print('---- arg1',arg1,'shape/len',arg1.shape,len(arg1.shape))
            if len(arg1.shape) == 1:
                arg1 = [arg1]
        elif isinstance(arg1,int) and isinstance(arg2,int):
            arg1 = np.zeros((arg1,arg2))
        elif isinstance(arg1,list):
            if arg1 == []:
                arg1 = np.zeros((0,0))  #[[]]
            elif not isinstance(arg1[0],list):
                arg1 = [arg1]
        else:
            raise Exception('bad arg')

        #print('@@@@@ arg1/cls',arg1,cls)
        obj = np.asarray(arg1).view(cls)
        obj.custom = data
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.custom = getattr(obj, 'custom', None)

    def ______str__(self,wide=False):   # string representation of list or matrix
        return "matrix"
        
    def _isa(self,obj,typ=None):
        if typ is None:
            print(type(obj),type(obj).__name__)
        return (type(obj).__name__ == typ)

    def __str__(self,wide=False):   # string representation of list or matrix
        m,n = self.shape
        txt = '[';  sepi = ''
        for i in range(0,m):
            txt += sepi;  sepi = '; ';  sepj = ''
            for j in range(0,n):
                if wide == False:
                    txt += sepj + "%g" % self[i,j]
                else:
                    s = "%4g" %M[i,j].item()
                    s = s if s[0:2] != '0.' else s[1:]
                    s = s if s[0:3] != '-0.' else '-'+s[2:]
                    txt += "%5s" % s
                sepj = ' '
        txt += ']'
        return txt

    def __repr__(self):
        return self.__str__()

    def t(self):                       # transpose
        return np.transpose(self)


In [58]:
# Example usage
arr = np.array([1, 2, 3, 4])

A = Matrix(arr, data="example")
print("A:",A)
print(A.__repr__())

empty = Matrix([])
print("empty:",empty,'shape:',empty.shape)

null = Matrix(0,0)
print("null:",null,'shape:',null.shape)

M=Matrix(2,3)

print('M: 2x3',M)
print("Custom parameter:", M.custom)


A: [1 2 3 4]
[1 2 3 4]
empty: [] shape: (0, 0)
null: [] shape: (0, 0)
M: 2x3 [0 0 0; 0 0 0]
Custom parameter: None


In [59]:
isinstance((7,8),tuple)

True

In [60]:
B=np.array([1,2,3]);B

array([1, 2, 3])

In [61]:
C=np.array([B]);C

array([[1, 2, 3]])

In [62]:
C=Matrix(C);C

[1 2 3]

In [63]:
C.t()

[1; 2; 3]